# Date for which meals should be recommended
dates:
  - 2023-12-26
  - 2023-12-27
  - 2023-12-28
  - 2023-12-29

# Rules to apply when deciding on a meal plan
# Entries should be names of elements of the Rules enum in src/rule.py
rules:
  - NOT_INDIAN_TWICE_WITHIN_TEN_DAYS
  - NOT_PASTA_TWICE_WITHIN_FIVE_DAYS
  - NOT_ROAST_ON_NON_SUNDAY
  - NOT_SAME_MEAL_WITHIN_SEVEN_DAYS

# NB: email_addresses are not currently in use in the project
email_addresses:
  - mealprepbot@gmail.com
  - testaddress@foo.bar
