name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black isort pytest
    - name: Check formatting with black
      run: |
        black . --line-length 100 --check
    - name: Check import sorting with isort
      run: |
        isort . --check --line-length 100 --multi-line 3 --lines-after-imports 2 \
        --force-sort-within-sections --dont-order-by-type --trailing-comma
    - name: Run unit tests
      run: |
        python -m unittest discover
    - name: Check provided recipes
      run: |
        python check_recipe_definitions.py
